### ISSUE TITLE
Fix DB name is hardcoding

### ISSUE THREAD

**Issue by mushon** [mushon/IWBA#17]
After the latest push I'm getting this error, it seems like it's expecting a DB in your name. @wonyoungso  Please let me know how do you suggest addressing this. Thanks!

```
dhcp-18-111-20-124:IWBA mushon$ bin/rails db:migrate RAILS_ENV=development
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  role "wonyoungso" does not exist
/Users/mushon/sites/IWBA/bin/rails:9:in `require'
/Users/mushon/sites/IWBA/bin/rails:9:in `<top (required)>'
/Users/mushon/sites/IWBA/bin/spring:14:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
PG::ConnectionBad: FATAL:  role "wonyoungso" does not exist
/Users/mushon/sites/IWBA/bin/rails:9:in `require'
/Users/mushon/sites/IWBA/bin/rails:9:in `<top (required)>'
/Users/mushon/sites/IWBA/bin/spring:14:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by wonyoungso** [comment]
Yes it's the database username issue. I added database.yml to gitignore and remove this file from repository--It means that you should make a new file.  To do this;
1. Pull the code
2. create a file in config/database.yml
3. Then copy them below and paste it into database.yml: 

development:
  adapter: postgresql
  encoding: unicode
  database: water_deposit_development
  pool: 5
  username: mushon
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: water_deposit_test
  pool: 5
  username: mushon
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: water_deposit_production
  pool: 5
  username: 
  password:

**Comment by mushon** [comment]
I followed your instruction and yet, errors…
Are the password lines supposed to stay empty?
I'm getting this error (from npm-debug.log):

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle IWBA@0.0.1~prestart: IWBA@0.0.1
6 silly lifecycle IWBA@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle IWBA@0.0.1~start: IWBA@0.0.1
8 verbose lifecycle IWBA@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle IWBA@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/mushon/sites/IWBA/node_modules/.bin:/usr/local/Cellar/node/6.2.1/bin:/Users/mushon/.rbenv/shims:/Users/mushon/.rbenv/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/GDAL.framework/Programs:/Library/Frameworks/GDAL.framework/Programs:/Library/Frameworks/GDAL.framework/Programs:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin
10 verbose lifecycle IWBA@0.0.1~start: CWD: /Users/mushon/sites/IWBA
11 silly lifecycle IWBA@0.0.1~start: Args: [ '-c', 'webpack-dev-server --config config/webpack.config.js' ]
12 silly lifecycle IWBA@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle IWBA@0.0.1~start: Failed to exec start script
14 verbose stack Error: IWBA@0.0.1 start: `webpack-dev-server --config config/webpack.config.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid IWBA@0.0.1
16 verbose cwd /Users/mushon/sites/IWBA
17 error Darwin 14.5.0
18 error argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.2.1
20 error npm  v3.9.3
21 error code ELIFECYCLE
22 error IWBA@0.0.1 start: `webpack-dev-server --config config/webpack.config.js`
22 error Exit status 1
23 error Failed at the IWBA@0.0.1 start script 'webpack-dev-server --config config/webpack.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the IWBA package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --config config/webpack.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs IWBA
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls IWBA
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mushon** [comment]
correction: solved after yml syntax correction and db migration. closing.
